version: '2'
services:
    httpd:
        image: enesgur/php-fpm:7.0
        container_name: web-server
        ports:
          - 80:80
          - 443:443
        volumes:
          - ./log/nginx:/var/log/nginx
          - ./nginx/conf/nginx.conf:/etc/nginx/nginx.conf
          - ./nginx/sites:/etc/nginx/sites-enabled
          - ./nginx/sites:/etc/nginx/sites-available
          - ./webroot:/var/www/html
          - ./php/php-fpm.ini:/etc/php/7.0/fpm/php.ini
          - ./php/php-fpm.conf:/etc/php/7.0/fpm/php-fpm.conf
        tty: true
    redis:
        image: redis:3.0
        ports:
          - 6379:6379
        volumes:
          - ./redis:/data
    mariadb:
        image: mariadb:10.1.14
        ports:
          - 3306:3306
        environment:
          - MYSQL_ALLOW_EMPTY_PASSWORD=yes
        volumes:
          - ./mysql:/var/lib/mysql
