version: '2'
services:
    httpd:
        image: enesgur/php-fpm:7.2
        container_name: web-server
        ports:
          - 80:80
          - 443:443
        volumes:
          - ./log/nginx:/var/log/nginx
          - ./nginx/conf/nginx.conf:/etc/nginx/nginx.conf
          - ./nginx/sites:/etc/nginx/sites-enabled
          - ./nginx/sites:/etc/nginx/sites-available
          - ./webroot:/var/www/html
          - ./php/php-fpm.ini:/etc/php/7.2/fpm/php.ini
          - ./php/php-fpm.conf:/etc/php/7.2/fpm/php-fpm.conf
        tty: true
